name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create APK Folder
        run: |
          mkdir apk
          cp -r www apk/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BakraCalculator
          path: apk
